default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root  # Change to your MySQL username (e.g., 'root')
  password: Kiran@6300  # Use ENV variable or plain password

development:
  <<: *default
  database: crmit_development  # Replace 'myapp' with your app's name

test:
  <<: *default
  database: crmit_test

production:
  <<: *default
  database: myapp_production
  username: myapp_user  # Replace with your production MySQL user
  password: <%= ENV['MYSQL_PASSWORD'] %>  # Make sure to set up an environment variable for this in production
